name: CI/CD Pipeline

on:
  push:
    branches: [ "master", "main" ]
  pull_request:
    branches: [ "master", "main" ]

jobs:
  build-and-test:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Setup .NET 9
      uses: actions/setup-dotnet@v3
      with:
        dotnet-version: '9.0.x'

    # در این مرحله هم ریستور می‌کند و هم پروژه را بدون ارور می‌سازد
    - name: Build project
      run: dotnet build CloudNativeInventory.sln --configuration Release

    # اجرای تست‌ها
    - name: Run tests
      run: dotnet test CloudNativeInventory.sln --configuration Release --no-build
