name: CI/CD Pipeline

on:
  push:
    branches: [ "master", "main" ]
  pull_request:
    branches: [ "master", "main" ]

jobs:
  build-and-test:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Setup .NET 9
      uses: actions/setup-dotnet@v3
      with:
        dotnet-version: '9.0.x'

    # ۱. بیلد کردن مستقیم پروژه API (بدون واسطه قرار دادن فایل sln)
    - name: Build API Project
      run: dotnet build CloudNativeInventory.Api/CloudNativeInventory.Api.csproj --configuration Release

    # ۲. بیلد و اجرای مستقیم پروژه تست
    - name: Run Tests
      run: dotnet test CloudNativeInventory.Tests/CloudNativeInventory.Tests.csproj --configuration Release
