name: CI/CD Pipeline

on:
  push:
    branches: [ "master", "main" ]
  pull_request:
    branches: [ "master", "main" ]

jobs:
  build-and-test:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Setup .NET 9
      uses: actions/setup-dotnet@v3
      with:
        dotnet-version: '9.0.x'

    # دانلود مستقیم پکیج‌ها برای تک تک پروژه‌ها به صورت تضمینی
    - name: Restore packages
      run: |
        dotnet restore CloudNativeInventory.Api/CloudNativeInventory.Api.csproj
        dotnet restore CloudNativeInventory.Tests/CloudNativeInventory.Tests.csproj

    # بیلد کردن پروژه بدون ایجاد محدودیت
    - name: Build project
      run: dotnet build CloudNativeInventory.sln --configuration Release

    # اجرای تست‌ها
    - name: Run tests
      run: dotnet test CloudNativeInventory.sln --configuration Release --no-build
